FOLDER=
MAIN_CLASS=
ARGS=

default:
	cd $(FOLDER) && javac Test.java && java Test

small:
	javac src/com/shijuan/algorism/$(MAIN_CLASS).java && cd bin && java com.shijuan.algorism.$(MAIN_CLASS) "$(ARGS)"