FOLDER=
MAIN_CLASS=
ARGS=

default:
	cd com.shijuan.$(FOLDER) && javac com.shijuan.$(FOLDER).Test.java && java com.shijuan.$(FOLDER).Test

small:
	javac src/com/shijuan/algorism/$(MAIN_CLASS).java && cd bin && java com.shijuan.algorism.$(MAIN_CLASS) "$(ARGS)"